### PR TITLE
midproject

### PR DESCRIPTION
**Pull request by Ivanclj**
In this updates, I modified three files that implemented the features to download data from target site, upload data to S3 bucket and create table in RDS or local based on configuration.

**Download data:**
src/load_my_data.py :  this script download data from my GitHub repo to ../data/data1.csv

**Upload data:**
src/upload_data.py: upload data to target s3 bucket

Requirement: boto 3 installed and have configured aws environment. (Check if have ~/.aws/credential file and if have access key and secret key in the file)

Argument to be specified in bash:

--input_path: local file path.

--bucket_name: target bucket name

--output_path: output file path

**Create database in RDS/local:**
src/sql/model_test.py: create table defined within script in either RDS or local based on argument

Requirement:
Have exported username, password, host and port for RDS as environment variables if want to use
RDS version.

Argument to be specified in bash:

--RDS: True to create in rds, default to create at local.

Note: there is a local logfile created by logger for information on the created table

### CODE REVIEW

**Comment by Cris7777** [comment]
**Functionality**

- src/load_my_data.py: this file successfully downloads data to designated path

- src/upload_data.py: this file successfully uploads data to my own s3 bucket

- src/sql/model.py: this file successfully creates a database both locally and on the RDS

**Comment by Cris7777** [comment]
**Readability & Code Quality**

-   The code is easy to follow. 

-   Design decisions are easy to understand both in individual scripts as well as in the code base as a whole

- Variable and method names are meaningful and all references are clear

-   Methods and functions are appropriately sized, suitable for testing

**Comment by Cris7777** [comment]
**Overall design**

-   The code being reviewed makes sense in the large context of the application, and it is consistent with the general approach that has so far been taken

-   It is modular and extensible

-   There are not issues with how the design might impact future development

**Comment by Cris7777** [comment]
**Testing**

-   The is code structured in a easily testable way

-   The PR does not include tests for the code where applicable, which need to be added later

**Comment by Cris7777** [comment]
**Documentation**

-   Methods and functions are properly documented

-   Inputs and outputs are explained and referenced by the parameter name

-   There are docstrings with descriptions of what functions methods are doing?

-   There is commentary to aid others to understand what is being done throughout the code

**Comment by Cris7777** [comment]
-  [README.md](https://github.com/Ivanclj/Smile/blob/master/README.md)

    -   It explains the overall design and approach to the problem
    
    -   it explains how someone else can get the code, build it and run it
   
-   Commit statements are meaningful

-    Changes and additions are explained in the PR

**Comment by Ivanclj** [comment]
> **Documentation**

> * There are docstrings with descriptions of what functions methods are doing?

Do you have a question here?

**Comment by Cris7777** [comment]
> > **Documentation**
> 
> > * There are docstrings with descriptions of what functions methods are doing?
> 
> Do you have a question here?

No, I think docstrings are good

**Comment by Cris7777** [comment]
You should add unit tests

**Comment by Cris7777** [comment]
Also, remember to update readme

**Comment by Ivanclj** [comment]
Added unit test for downloading data. Also fixed README

**Pull request merged**
